name: 'E-Extend'
 
on:
  #push:
  schedule:
    # UTC time (国内 UTC+8)
     - cron: '32 1 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job-1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:    
    - name: get tomorrow
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: | 
        echo "::set-env name=tomorrow::$(date --date="next day" +%d)"
  job-2:
    needs: [job-1]
    runs-on: macos-12
    steps:     
    - name: 明天是 21
      if: env.tomorrow == 21
        - name: 'Checkout codes'
          uses: actions/checkout@v2

        - name: 'Environment Settings'
          run: |
            pip3 install -r ./requirements.txt
            brew upgrade --cask google-chrome            
        - name: 'Renew'
          env:
            EU_USER_ID: ${{ secrets.EU_USER_ID }}
            EU_PASS_WD: ${{ secrets.EU_PASS_WD }}
            CAPTCHA_USER_ID: ${{ secrets.CAPTCHA_USER_ID }}
            CAPTCHA_APIKEY: ${{ secrets.CAPTCHA_APIKEY }}
            MAILPARSER: ${{ secrets.MAILPARSER }}
            BARK_KEY: ${{ secrets.BARK_KEY }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}
            
          run: |
            python3 ./main.py
